# Generated by Django 4.2.7 on 2023-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeet', '0002_genre_movie_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
